version: 2

sources:
  - name: raw
    database: ECOMMERCE_ANALYTICS
    schema: RAW
    tables:
      - name: raw_customers
      - name: raw_products
      - name: raw_orders
      - name: raw_order_items
